services:
  litellm:
    build:
      context: .
      args:
        target: runtime
    image: ghcr.io/berriai/litellm:main-latest
    pull_policy: always
    ########################################
    # Uncomment these lines to start proxy with a config.yaml file ##
    volumes:
     - ./config.yaml:/app/config.yaml
     - /home/ubuntu/.config/gcloud/application_default_credentials.json:/home/ubuntu/.config/gcloud/application_default_credentials.json
    command:
     - "--config"   
     - "/app/config.yaml"
    ##############################################
    ports:
      - "4000:4000" # Map the container port to the host, change the host port if necessary
    environment:
      DATABASE_URL: "postgresql://llmproxy:dbpassword9090@db:5432/litellm"
      STORE_MODEL_IN_DB: "True" # allows adding models to proxy via UI
      GOOGLE_APPLICATION_CREDENTIALS: "/home/ubuntu/.config/gcloud/application_default_credentials.json"
    env_file:
      - .env # Load local .env file
    restart: unless-stopped # Add restart policy to make service more resilient
    depends_on:
      db:
        condition: service_healthy # Ensures db is fully healthy before starting
    # Temporarily removing health check to see if service starts properly

  db:
    image: postgres:16
    restart: always
    container_name: litellm_db
    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: llmproxy
      POSTGRES_PASSWORD: dbpassword9090
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists Postgres data across container restarts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d litellm -U llmproxy"]
      interval: 1s
      timeout: 5s
      retries: 10

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  postgres_data:
    name: litellm_postgres_data # Named volume for Postgres data persistence
  qdrant_storage:
    name: litellm_qdrant_storage
